export function renderPortfolio(s,features){
 const out={},byName=new Map(s.repositories.map(r=>[r.name,r])),fm=new Map(features.map(f=>[f.name,f]));
 const formats={source:['Source and web files','源码与网页文件'],archive:['Downloadable archive','压缩包分发'],documents:['Documentation and research','文档与研究材料']};
 const clean=x=>String(x||'—').replace(/\|/g,'\\|').replace(/\r?\n/g,' ').replace(/</g,'&lt;').replace(/>/g,'&gt;');
 const file=(r,p)=>r.url+'/blob/'+encodeURIComponent(r.default_branch)+'/'+p.split('/').map(encodeURIComponent).join('/');
 const put=(p,lines)=>out[p]=(Array.isArray(lines)?lines.join('\n'):lines).trimEnd()+'\n';
 for(const r of s.repositories){
  const f=fm.get(r.name),lines=['# '+r.name,'','[Repository / 仓库]('+r.url+') · [Research area / 研究领域](../directory/'+r.category+'.md) · [All projects / 全部项目](../REPOSITORY_DIRECTORY.md)','',r.description,''];
  if(r.description_zh)lines.push(r.description_zh,'');
  lines.push('## Get started / 开始使用','','[Project instructions / 项目说明]('+file(r,r.readme_path)+') · [Download repository ZIP / 下载仓库ZIP]('+r.url+'/archive/refs/heads/'+encodeURIComponent(r.default_branch)+'.zip)','');
  if(f)lines.push('[Practical guide / 操作导读]('+file(r,'GETTING_STARTED.md')+') · [Entry file / 入口文件]('+file(r,f.entry)+')','');
  const advice={archive:['Download a named package below, extract it and read the instructions inside its project folder.','先下载下方具名交付包，解压后阅读项目目录内的说明。'],source:['Follow the repository instructions for dependencies and the documented entry point. Download HTML tools before opening them in a browser.','按项目说明核对依赖与运行入口。HTML工具请先下载，再用浏览器打开。'],documents:['Start with the published research documents and attachments. This inspected tree is presented as documentation.','先阅读公开研究文档与附件；本次检查到的文件树以文档材料呈现。']};
  lines.push(...advice[r.format],'');
  if(r.name==='DIKWP_ASEAN_SolutionForge_v1.0.0')lines.push('**Publication status / 发布状态:** the public repository contains its introduction. The original complete source package still needs to be imported. / 当前公开仓库包含项目介绍，原始完整源码包尚待导入。','');
  if(r.archives.length)lines.push('### Delivery packages / 交付包','',...r.archives.map(p=>'- ['+clean(p)+']('+file(r,p)+'?raw=true)'),'');
  lines.push('## Project record / 项目记录','','| Field / 字段 | Value / 内容 |','|---|---|',
   ...[['Research area / 领域',r.category_en+' · '+r.category_zh],['Distribution / 形式',formats[r.format].join(' · ')],['Branch / 分支',r.default_branch],['Language metadata / 语言元数据',r.language],['License metadata / 许可元数据',r.license],['Visible files / 可见文件',String(r.file_count)],['Code and web files / 代码与网页文件',String(r.code_and_web_file_count)],['Test files observed / 已见测试文件',String(r.test_file_count)],['Checked / 检查日期',r.checked_on],['Summary source / 简介来源',r.description_source]].map(([k,v])=>'| '+k+' | '+clean(v)+' |'),'');
  if(r.license_path)lines.push('[Read the license / 阅读许可]('+file(r,r.license_path)+') · Retain component licenses and notices / 保留各组件许可与声明。','');
  if(r.topics.length)lines.push('**Topics / 主题:** '+r.topics.join(', '),'');
  lines.push('## Files to inspect / 建议阅读','',...r.guides.map(p=>'- ['+clean(p)+']('+file(r,p)+')'),'','## Verification / 验证入口','','File availability, test-file presence and successful execution are recorded separately. Follow a dated workflow run or reproduction record for execution evidence.','文件可用性、测试文件存在与实际运行通过分别记录；运行证据请查看带日期和版本的工作流或复现记录。','');
  if(r.workflows.length)lines.push(...r.workflows.map(p=>'- ['+clean(p)+']('+file(r,p)+')'),'','[GitHub Actions runs]('+r.url+'/actions)','');
  if(f?.workflow)lines.push('[Successful workflow on the guide publication commit]('+f.workflow.url+') · Commit: '+f.commit+' · Checked: '+f.workflow.checked_on,'');
  lines.push('Inspected Git tree: '+r.tree_sha+'. [Inventory method / 清单方法](../PORTFOLIO_MAINTENANCE.md).','');
  if(r.related.length)lines.push('## Related research / 相关研究','',...r.related.filter(x=>byName.has(x.name)).map(x=>'- ['+x.name+'](../'+byName.get(x.name).detail_path+')'),'','These are research navigation links. / 以上为研究导航关系。','');
  lines.push('## Cite and collaborate / 引用与合作','','[Citation guide / 引用指南](../CITING.md) · [Written collaboration / 书面合作](../COLLABORATE.md)','','Identify the repository, version, input scope and expected artifact in a proposal. / 合作请明确仓库、版本、输入范围与预期交付物。');
  put(r.detail_path,lines);
 }
 for(const c of s.categories)for(const zh of [false,true]){
  const suffix=zh?'.zh-CN':'',rows=s.repositories.filter(r=>r.category===c.id),starters=rows.filter(r=>r.featured);
  const lines=['# '+c[zh?'zh':'en'],'','**'+rows.length+' '+(zh?'个公开仓库':'public repositories')+' · '+s.checked_on+'**','','[All areas / 全部领域](../REPOSITORY_DIRECTORY'+suffix+'.md) · [English]('+c.id+'.md) · [中文]('+c.id+'.zh-CN.md)',''];
  if(starters.length)lines.push('## '+(zh?'推荐起点':'Suggested starting points'),'',...starters.map(r=>'- ['+fm.get(r.name).title+'](../'+r.detail_path+') — '+fm.get(r.name)[zh?'zh':'en']),'');
  lines.push(zh?'简介概括项目声明的用途。详情页提供下载、文件与验证入口。':'Summaries describe the published project purpose. Detail pages provide downloads, inspected files and verification.','',zh?'| 项目与详情 | 用途 | 交付形式 | 许可 |':'| Project and details | Purpose | Distribution | License |','|---|---|---|---|',...rows.map(r=>'| ['+r.name+'](../'+r.detail_path+') · [GitHub]('+r.url+') | '+clean(zh&&r.description_zh?r.description_zh:r.description)+' | '+formats[r.format][zh?1:0]+' | '+clean(r.license)+' |'));
  put('directory/'+c.id+suffix+'.md',lines);
 }
 for(const zh of [false,true]){
  const suffix=zh?'.zh-CN':'';
  const lines=['# '+s.repository_count+(zh?'个公开仓库：研究与应用目录':' public repositories: research and applications'),'','**'+s.repository_count+' · '+s.categories.length+' · 13** — '+(zh?'公开仓库 · 研究领域 · 主页语言':'public repositories · research areas · profile languages'),'','[English](REPOSITORY_DIRECTORY.md) · [中文](REPOSITORY_DIRECTORY.zh-CN.md) · [Profile](README'+suffix+'.md) · [Project finder](PROJECT_FINDER'+suffix+'.md) · [JSON](REPOSITORY_DIRECTORY.json)','',(zh?'仓库身份、元数据与完整Git文件树核对日期：':'Repository identities, metadata and complete Git file trees inspected: ')+s.checked_on+'.','',zh?'| 研究领域 | 仓库数 | 推荐入口 |':'| Research area | Repositories | Starting points |','|---|---:|---|'];
  for(const c of s.categories)lines.push('| ['+c[zh?'zh':'en']+'](directory/'+c.id+suffix+'.md) | '+c.count+' | '+c.featured.filter(n=>byName.has(n)).slice(0,2).map(n=>'['+(fm.get(n)?.title||n)+']('+byName.get(n).detail_path+')').join(' · ')+' |');
  lines.push('','## '+(zh?'按交付方式开始':'Choose a distribution'),'',zh?'| 形式 | 数量 |':'| Format | Count |','|---|---:|',...Object.keys(formats).map(k=>'| '+formats[k][zh?1:0]+' | '+s.format_counts[k]+' |'),'',zh?'交付形式描述实际可见文件，运行结果需查看各项目独立的验证记录。':'Distribution labels describe available files. Execution results are linked independently for each project.','','[Project finder / 项目选择](PROJECT_FINDER'+suffix+'.md) · [Offline search / 离线搜索](catalog/README'+suffix+'.md) · [Inventory method](PORTFOLIO_MAINTENANCE.md)');
  put('REPOSITORY_DIRECTORY'+suffix+'.md',lines);
  put('PROJECT_FINDER'+suffix+'.md',['# '+(zh?'从你的问题进入DIKWP':'Find the DIKWP project for your question'),'','[English](PROJECT_FINDER.md) · [中文](PROJECT_FINDER.zh-CN.md) · [Full directory](REPOSITORY_DIRECTORY.md)','',zh?'选择希望检查的结果，再进入对应仓库的操作导读。':'Choose the result you want to inspect, then follow the walkthrough in the corresponding repository.','',zh?'| 项目 | 可以探索什么 | 开始使用 |':'| Project | What to explore | Get started |','|---|---|---|',...features.map(f=>{const r=byName.get(f.name);return '| ['+f.title+']('+r.detail_path+') | '+f[zh?'zh':'en']+' | [Guide / 操作导读]('+file(r,'GETTING_STARTED.md')+') |';}),'','## '+(zh?'带着一个可交付成果开始':'Start with one inspectable artifact'),'',zh?'研究者可以提交最小反例、复现记录或证据补充；教师可以使用OpenStudio设计课程与实验；合作机构可以选定任务、数据范围、源码版本与验收标准，以书面材料推进试点。':'Researchers can contribute a minimal counterexample, reproduction record or source correction. Teachers can build lessons and experiments with OpenStudio. Collaborators can define a task, data scope, source revision and acceptance criteria, then develop a pilot through written review.','','[Collaboration / 合作](COLLABORATE'+suffix+'.md) · [Citation / 引用](CITING'+suffix+'.md)']);
  put('CURRENT_STATUS'+suffix+'.md',['# '+(zh?'开放研究版图：当前状态':'Current open research portfolio'),'','[English](CURRENT_STATUS.md) · [中文](CURRENT_STATUS.zh-CN.md) · [Profile](README'+suffix+'.md)','','**'+s.checked_on+' · '+s.repository_count+' repositories · 12 research areas · 13 profile languages**','',zh?'本轮更新覆盖489个项目详情、12个领域的中英文目录、13语种主页导航，以及直接提交到11个代表仓库的操作导读。':'This refresh covers 489 project detail pages, bilingual directories for 12 fields, navigation in 13 profile languages and practical guides committed to 11 featured repositories.','',...Object.keys(formats).map(k=>'- '+formats[k][zh?1:0]+': '+s.format_counts[k]),'',zh?'OpenStudio已完整发布。SolutionForge当前包含项目介绍；原始完整源码包仍待导入。':'OpenStudio is fully published. SolutionForge currently contains its project introduction; import of its original full source package remains pending.','','[Project finder](PROJECT_FINDER'+suffix+'.md) · [Verification and downloads](catalog/README'+suffix+'.md) · [Refresh record](PROFILE_REFRESH_2026-09-18.md) · [Snapshot](research/PORTFOLIO_SNAPSHOT.json)']);
  put('catalog/README'+suffix+'.md',['# '+(zh?'源码、下载与验证目录':'Source, download and verification catalog'),'','[English](README.md) · [中文](README.zh-CN.md) · [Full directory](../REPOSITORY_DIRECTORY'+suffix+'.md) · [JSON](CATALOG.json)','','## '+(zh?'离线搜索全部项目':'Search the complete portfolio offline'),'',zh?'[下载项目搜索页](https://raw.githubusercontent.com/YucongDuan/YucongDuan/main/catalog/index.html)，保存为HTML文件后用浏览器打开，即可按关键词、领域、交付形式筛选489个项目。搜索数据内置；打开仓库链接需要联网。':'[Download the project explorer](https://raw.githubusercontent.com/YucongDuan/YucongDuan/main/catalog/index.html), save it as HTML and open it in a browser. Search all 489 projects by keyword, research area and distribution format. Search data is embedded; repository links require internet access.','','## '+(zh?'选择操作路线':'Choose a practical walkthrough'),'','[11 guided projects / 11个项目操作路线](../PROJECT_FINDER'+suffix+'.md)','',zh?'ZIP项目先解压，再阅读包内README；GitHub显示HTML源码时，应先下载项目后本地打开。':'Extract ZIP-distributed projects before following the inner README. When GitHub displays HTML source, download the project and open the file locally.','','## '+(zh?'查看验证记录':'Inspect verification evidence'),'',zh?'九个已有工作流的代表项目，本次导读提交均通过自动测试。各结果绑定具体提交、时间和工作流链接；其余项目不据此声称运行通过。':'Nine existing featured-project workflows passed on the published guide commits. Each result identifies a revision, date and workflow link; it is not an execution claim for the other projects.','','[Publication commits and workflow results / 提交与验证结果](../PROFILE_REFRESH_2026-09-18.md) · [Earlier engineering records](../ENGINEERING_STATUS.md) · [Inventory method](../PORTFOLIO_MAINTENANCE.md)','',zh?'SolutionForge目前仍为项目介绍仓库，完整源码包尚待导入。':'SolutionForge currently remains an introduction repository; its complete source package still needs to be imported.']);
 }
 put('REPOSITORY_DIRECTORY.json',JSON.stringify({schema_version:2,summary:{repository_count:s.repository_count,checked_on:s.checked_on,categories:s.categories},repositories:s.repositories.map(r=>({...r,html_url:r.url,public_description:r.description,metadata_checked_at:r.checked_on}))},null,2));
 put('catalog/CATALOG.json',JSON.stringify(s,null,2));
 put('REPOSITORY_SUMMARIES.en.json',JSON.stringify({schema_version:2,inventory_date:s.checked_on,repository_count:s.repository_count,categories:s.categories,repositories:s.repositories.map(r=>({name:r.name,url:r.url,category:r.category,summary:r.description,summary_source:r.description_source,detail_path:r.detail_path}))},null,2));
 put('PORTFOLIO_MAINTENANCE.md',['# Portfolio inventory and maintenance','','The current [snapshot](research/PORTFOLIO_SNAPSHOT.json) records '+s.repository_count+' distinct public repository identities, current metadata and complete Git file trees, checked '+s.checked_on+'.','','## Interpreting the records','','- Source and web files: recognized code or HTML/CSS extensions are present in the inspected tree.','- Downloadable archive: a named archive is present near the root without visible source or web files.','- Documentation and research: introductions, documents or other research materials.','- Test-file counts describe files. A completed workflow run supplies independent execution evidence at a particular revision.','- License metadata is a navigation aid. Follow each project and component license.','- Summaries use current metadata, existing editorial summaries, or curated descriptions grounded in featured project instructions. Category assignments retain the established research taxonomy.','','## Reproduce the pages','','Node.js 22; no package installation is required. The offline build is deterministic from committed inputs.','','~~~bash','node scripts/build_portfolio.mjs --write','node scripts/build_portfolio.mjs --check','node scripts/validate_portfolio.mjs','~~~','','The refresh workflow collects public metadata and file trees, generates pages, validates them and publishes with a normal fast-forward Git commit. It has no scheduled trigger. The separate consistency workflow uses committed inputs and read-only repository permission.','','Snapshots retain the inspected revision; later edits do not silently change recorded evidence. [Historical catalog before this refresh](https://github.com/YucongDuan/YucongDuan/blob/e00529da57576fce7b02b5814e3a62012a48556c/catalog/CATALOG.json).','','## 中文说明','','本轮清单核对489个公开仓库的身份、元数据与完整文件树，每个项目提供独立详情页。文件形式、测试文件数量与实际运行证据分别记录。目录由已提交的快照生成，可以复现并检查链接。','','SolutionForge的原始完整源码导入因工作环境断开而待补齐。该项目按当前公开文件如实标为文档，未声称已发布可运行源码。']);
 return out;
}
