export function renderExplorer(s){
 const data={checked_on:s.checked_on,categories:s.categories,repositories:s.repositories.map(r=>({name:r.name,url:r.url,description:r.description,description_zh:r.description_zh,category:r.category,category_en:r.category_en,category_zh:r.category_zh,format:r.format,featured:r.featured,detail_path:r.detail_path}))};
 const script=[
  "'use strict';",
  "const data=JSON.parse(document.getElementById('inventory').textContent),get=id=>document.getElementById(id);",
  "const query=get('query'),area=get('area'),format=get('format'),featured=get('featured'),cards=get('cards'),more=get('more');",
  "const labels={source:'Source & web / 源码与网页',archive:'Archive / 压缩包',documents:'Research documents / 研究文档'};",
  "for(const c of data.categories){const o=document.createElement('option');o.value=c.id;o.textContent=c.en+' · '+c.zh;area.append(o);}",
  "const sorted=[...data.repositories].sort((a,b)=>Number(b.featured)-Number(a.featured)||a.name.localeCompare(b.name));let limit=30;",
  "function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;}",
  "function link(text,href){const n=el('a','',text);n.href=href;return n;}",
  "function render(){const terms=query.value.trim().toLocaleLowerCase().split(/\\s+/).filter(Boolean);",
  "const matched=sorted.filter(r=>(!area.value||r.category===area.value)&&(!format.value||r.format===format.value)&&(!featured.checked||r.featured)&&terms.every(t=>(r.name+' '+r.description+' '+(r.description_zh||'')+' '+r.category_en+' '+r.category_zh).toLocaleLowerCase().includes(t)));",
  "const shown=matched.slice(0,limit),fragment=document.createDocumentFragment();",
  "for(const r of shown){const card=el('article','card'),title=el('h2');title.append(link(r.name,r.url));card.append(el('p','meta',labels[r.format]+(r.featured?' · Guided / 附导读':'')),title,el('p','description',r.description));",
  "if(r.description_zh&&r.description_zh!==r.description)card.append(el('p','description zh',r.description_zh));card.append(el('p','field',r.category_en+' · '+r.category_zh));",
  "const nav=el('div','links');nav.append(link('Details / 项目详情','https://github.com/YucongDuan/YucongDuan/blob/main/'+r.detail_path),link('Repository / 仓库',r.url));if(r.featured)nav.append(link('Guide / 操作导读',r.url+'/blob/main/GETTING_STARTED.md'));card.append(nav);fragment.append(card);}",
  "cards.replaceChildren(fragment);get('count').textContent=matched.length+' matching projects / 个匹配项目 · '+shown.length+' shown / 已显示';get('empty').hidden=matched.length!==0;more.hidden=shown.length>=matched.length;}",
  "for(const control of [query,area,format,featured])control.addEventListener(control===query?'input':'change',()=>{limit=30;render();});",
  "more.addEventListener('click',()=>{limit+=30;render();});get('reset').addEventListener('click',()=>{query.value='';area.value='';format.value='';featured.checked=false;limit=30;render();query.focus();});render();"
 ].join('\n');
 return [
  '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">',
  '<title>DIKWP Research Explorer · '+s.repository_count+' projects</title>',
  '<meta name="description" content="Explore Yucong Duan’s research portfolio by purpose, topic and available source or downloads.">',
  '<style>',
  ':root{color-scheme:light;--ink:#183f39;--muted:#50665e;--paper:#f4f3ec;--line:#c9d7cf;--accent:#165c4a}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:16px/1.6 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:var(--accent);text-underline-offset:3px}a:focus-visible,button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #bf861b;outline-offset:3px}',
  'header{background:#123e35;color:#fff;padding:48px max(24px,calc((100vw - 1180px)/2)) 40px}header a{color:#c9ead9}.eyebrow{font-size:.85rem;letter-spacing:.12em;text-transform:uppercase;color:#c9ead9}h1{font-size:clamp(2rem,5vw,3.6rem);line-height:1.1;letter-spacing:-.035em;margin:18px 0}header p{max-width:780px}.facts{display:flex;gap:28px;flex-wrap:wrap;margin:26px 0}.facts strong{font-size:1.6rem;display:block}.facts span{font-size:.9rem;color:#d1e3d8}.topnav{display:flex;gap:18px;flex-wrap:wrap}',
  'main{max-width:1228px;padding:28px 24px 60px;margin:auto}.controls{display:grid;grid-template-columns:2fr 1.4fr 1fr;gap:16px;background:#fff;padding:24px;border:1px solid var(--line);border-radius:16px}label{font-size:.9rem;font-weight:650;display:block}input[type=search],select{font:inherit;color:inherit;background:#fff;border:1px solid #8aa198;border-radius:8px;min-height:46px;width:100%;padding:10px;margin-top:6px}.extra{grid-column:1/-1;display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.check{display:flex;align-items:center;gap:8px}.check input{width:18px;height:18px;accent-color:var(--accent)}button{border:1px solid var(--accent);border-radius:8px;color:var(--accent);background:#fff;padding:10px 18px;font:inherit;cursor:pointer}button:hover{background:#e4eee7}.status{display:flex;justify-content:space-between;gap:15px;margin:24px 0;color:var(--muted);font-size:.9rem}',
  '.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.card{display:flex;flex-direction:column;background:#fff;border:1px solid var(--line);border-radius:14px;padding:24px;min-width:0}.meta{font-size:.75rem;text-transform:uppercase;letter-spacing:.04em;color:var(--accent);margin:0 0 12px}.card h2{font-size:1.12rem;line-height:1.4;margin:0 0 12px;overflow-wrap:anywhere}.card h2 a{text-decoration:none}.card h2 a:hover{text-decoration:underline}.description{font-size:.95rem;margin:0 0 12px;overflow-wrap:anywhere}.zh{color:var(--muted)}.field{font-size:.78rem;color:var(--muted);margin:8px 0 16px}.links{display:flex;flex-wrap:wrap;gap:14px;font-size:.85rem;margin-top:auto;border-top:1px solid #e0e7e1;padding-top:15px}.more{text-align:center;padding:28px 0}.note{border-top:1px solid var(--line);padding-top:24px;color:var(--muted);font-size:.88rem}.empty{padding:30px;background:#fff;border-radius:12px}footer{max-width:1228px;margin:auto;padding:0 24px 40px;color:var(--muted);font-size:.85rem}[hidden]{display:none!important}@media(max-width:760px){header{padding:32px 24px}.controls,.grid{grid-template-columns:1fr}.facts{gap:20px}.controls{padding:18px}.status{display:block}.card{padding:20px}}',
  '</style></head><body>',
  '<header><div class="eyebrow">Yucong Duan · 段玉聪 · Open research</div><h1>DIKWP Research Explorer</h1><p>Find a research question, a working entry point and the material behind it.<br><span lang="zh-CN">从研究问题找到项目入口，查看源码、交付包与验证记录。</span></p>',
  '<div class="facts"><div><strong>'+s.repository_count+'</strong><span>Public repositories / 公开仓库</span></div><div><strong>'+s.categories.length+'</strong><span>Research areas / 研究领域</span></div><div><strong>11</strong><span>Practical guides / 操作导读</span></div></div>',
  '<nav class="topnav" aria-label="Main"><a href="https://github.com/YucongDuan">Profile / 主页</a><a href="https://github.com/YucongDuan/YucongDuan/blob/main/PROJECT_FINDER.md">Start a project</a><a href="https://github.com/YucongDuan/YucongDuan/blob/main/PROJECT_FINDER.zh-CN.md" lang="zh-CN">项目选择</a><a href="https://github.com/YucongDuan/YucongDuan/blob/main/COLLABORATE.md">Collaborate / 合作</a></nav></header>',
  '<main><section class="controls" aria-label="Project filters"><div><label for="query">Search / 搜索项目</label><input type="search" id="query" placeholder="Purpose, medicine, 意图, OpenStudio…" autocomplete="off"></div>',
  '<div><label for="area">Research area / 研究领域</label><select id="area"><option value="">All areas / 全部领域</option></select></div>',
  '<div><label for="format">Available material / 交付形式</label><select id="format"><option value="">All formats / 全部形式</option><option value="source">Source &amp; web / 源码与网页</option><option value="archive">Archive / 压缩包</option><option value="documents">Documents / 文档</option></select></div>',
  '<div class="extra"><label class="check"><input type="checkbox" id="featured">With a practical guide / 附操作导读</label><button type="button" id="reset">Reset / 重置</button></div></section>',
  '<div class="status"><span id="count" role="status" aria-live="polite"></span><span>Inventory / 清单日期: '+s.checked_on+'</span></div>',
  '<noscript><p>JavaScript is needed for filtering. Browse the <a href="https://github.com/YucongDuan/YucongDuan/blob/main/REPOSITORY_DIRECTORY.md">complete directory</a> or <a href="https://github.com/YucongDuan/YucongDuan/blob/main/REPOSITORY_DIRECTORY.zh-CN.md">中文目录</a>.</p></noscript>',
  '<p id="empty" class="empty" hidden>No matching projects. Try fewer keywords or clear a filter. / 未找到匹配项目，请减少关键词或清除筛选条件。</p><section id="cards" class="grid" aria-label="Matching projects"></section><div class="more"><button type="button" id="more" hidden>Show 30 more / 再显示30个</button></div>',
  '<p class="note">Search works offline; following repository links requires internet access. Distribution labels describe inspected files. Execution evidence is linked in each project record.<br><span lang="zh-CN">搜索可离线使用，打开仓库链接需要联网。交付形式依据已检查的文件；实际运行证据请查看各项目详情。</span></p></main>',
  '<footer><a href="https://github.com/YucongDuan/YucongDuan/blob/main/PORTFOLIO_MAINTENANCE.md">Inventory method / 清单方法</a> · <a href="https://github.com/YucongDuan/YucongDuan/blob/main/CITING.md">Cite / 引用</a></footer>',
  '<script type="application/json" id="inventory">'+JSON.stringify(data).replace(/</g,'\\u003c')+'</script>',
  '<script>'+script+'</script></body></html>'
 ].join('\n')+'\n';
}
